name: enterprise-script-service

up:
  - ruby:
      version: 2.5.8
  - bundler
  - submodules

commands:
  recompile:
    syntax: ""
    desc: "Compiles native extention"
    run: bin/rake clobber compile
  compile:
    syntax: ""
    desc: "Compiles native extention"
    run: bin/rake compile
  spec:
    syntax: ""
    desc: "Run specs"
    run: bin/rake spec
